### ISSUE TITLE
[FRONTEND] Add a variable in all the posts.

### ISSUE THREAD

**Issue by anonfaded** [fadedhood/fadedhood.github.io#7]
# There is a variable missing in our post's markdown files.
## Steps to resolve the issue:
- Fork and clone the repo to local machine.
- Navigate to `_posts` directory where you will see 7 posts.
- You are required to add the following `code` to the last line of yaml front matter at all the `7` posts.
```yml
comments: true
```
#  This is how it will look when you add the above code at the last line:
```yml
---
layout: post
title: Intro To Fadedhood
image:
  path: /assets/img/post1/cyber-lock-optimised.webp
  lqip: data:image/webp;base64,UklGRpoAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSDIAAAARL0AmbZurmr57yyIiqE8oiG0bejIYEQTgqiDA9vqnsUSI6H+oAERp2HZ65qP/VIAWAFZQOCBCAAAA8AEAnQEqEAAIAAVAfCWkAALp8sF8rgRgAP7o9FDvMCkMde9PK7euH5M1m6VWoDXf2FkP3BqV0ZYbO6NA/VFIAAAA
comments: true
---
```
- Add the code at the last line  above the `---`.
